name: pubquiz-server
version: 0.1.0.0
github: "nikitaDanilenko/pubquiz-server"
license: BSD3
author: "Nikita Danilenko"
maintainer: "nikita.danilenko.is@gmail.com"
copyright: "2026 Nikita Danilenko"

extra-source-files:
  - Readme.md

# Metadata used when publishing your package
synopsis: Host server for pub quiz application.
category: Web

description: Please see the README on GitHub at <https://github.com/nikitaDanilenko/pubquiz-server#readme>

# Generate .hie files for better HLS navigation
ghc-options:
  - -fwrite-ide-info
  - -hiedir=.hie

dependencies:
  - aeson
  - base
  - bcrypt
  - bytestring
  - containers
  - dhall
  - jose
  - monad-logger
  - mtl
  - openapi3
  - persistent
  - persistent-postgresql
  - persistent-template
  - resource-pool
  - servant
  - servant-auth
  - servant-auth-server
  - servant-openapi3
  - servant-server
  - text
  - time
  - transformers
  - warp

library:
  source-dirs: src

executables:
  pubquiz-server:
    main: Main.hs
    source-dirs: app
    dependencies:
      - pubquiz-server
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

tests:
  pubquiz-server-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - pubquiz-server
      - hspec
      - hspec-discover
      - hspec-wai
      - hspec-wai-json
      - http-types
      - testcontainers
      - wai
      - wai-extra
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
