name:                pubquiz-server
version:             0.1.0.0
github:              "nikitaDanilenko/pubquiz-server"
license:             BSD3
author:              "Nikita Danilenko"
maintainer:          "nikita.danilenko.is@gmail.com"
copyright:           "2020 Nikita Danilenko"

extra-source-files:
- Readme.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Host server for pub quiz application.
category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/pubquiz-server-stack#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring >=0.10 && <0.11
- containers >=0.1 && < 1
- snap >=1.1 && <1.2
- text >=1.2 && <1.3
- snap-server >=1.1 && <1.2
- snap-core >=1.0 && <2
- snap-loader-static >= 0.9 && < 1.1
- lens >=4.17 && <4.18
- filepath >= 1.4 && < 2.0
- cryptonite >= 0.2 && < 1
- directory >= 1 && < 2
- process >= 1 && < 2
- random >= 1 && < 2
- split >= 0.2 && < 1
- parsec >= 3.1 && < 4
- extra >= 1 && < 2
- colour >= 2.1 && < 3
- HaTeX >= 3 && < 4
- persistent
- persistent-postgresql
- persistent-template
- monad-logger
- time
- path-pieces
- transformers
- resourcet
- aeson
- case-insensitive


library:
  source-dirs: src

executables:
  pubquiz-server-exe:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pubquiz-server